delete feature (WIP)
projectsecure/projectsecure-api pull request #47
Opened 2016-12-30 11:21 UTC by boeckhoff

2016-12-30 13:12 UTC, nikriek requested changes

2016-12-30 13:12 UTC, nikriek commented on users/views.py
> +    @list_route(methods=['post'], permission_classes=[AllowAny])
Please create a new view. You don't need the decorator as we are Not using viewsets anymore.

2016-12-30 13:21 UTC, nikriek commented on users/urls.py
> +    url(r'^auth/delete$', delete_jwt_token, name='delete-jwt-verify'),
You are Not deleting authentication but the user. Name the endpoint sonerhing like `/me`

2016-12-30 13:40 UTC, nicoknoll commented on users/urls.py
> +    url(r'^auth/delete$', delete_jwt_token, name='delete-jwt-verify'),
Just use the DEL method at /users/me endpoint

2016-12-30 13:40 UTC, nikriek commented on users/urls.py
> +    url(r'^auth/delete$', delete_jwt_token, name='delete-jwt-verify'),
Jep 👍

2016-12-30 13:40 UTC, nicoknoll commented on users/views.py
> +    @list_route(methods=['post'], permission_classes=[AllowAny])
and don't use post but DELETE

2016-12-30 13:41 UTC, nikriek commented on users/urls.py
> +    url(r'^auth/delete$', delete_jwt_token, name='delete-jwt-verify'),
It's inserted automatically with viewsets

2016-12-30 13:41 UTC, nikriek commented on users/views.py
> +    @list_route(methods=['post'], permission_classes=[AllowAny])
And remove permission_classes ;)

2016-12-30 13:42 UTC, nicoknoll commented on users/urls.py
> +    url(r'^auth/delete$', delete_jwt_token, name='delete-jwt-verify'),
![rest-presentation-9-638](https://cloud.githubusercontent.com/assets/1143670/21565952/2effd63c-ce9e-11e6-855c-b19a18ee799a.jpg)

2017-01-11 00:34 UTC, boeckhoff commented
tests will follow

2017-01-28 14:35 UTC, merged